/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BoardsCreateRouteImport } from './routes/boards/create'
import { Route as BoardsBoardIdRouteImport } from './routes/boards/$boardId'
import { Route as BoardsBoardIdIndexRouteImport } from './routes/boards/$boardId/index'
import { Route as TasksUpdateTaskIdRouteImport } from './routes/tasks/update/$taskId'
import { Route as TasksDeleteTaskIdRouteImport } from './routes/tasks/delete/$taskId'
import { Route as ColumnsUpdateColumnIdRouteImport } from './routes/columns/update/$columnId'
import { Route as ColumnsDeleteColumnIdRouteImport } from './routes/columns/delete/$columnId'
import { Route as BoardsUpdateBoardIdRouteImport } from './routes/boards/update/$boardId'
import { Route as BoardsDeleteBoardIdRouteImport } from './routes/boards/delete/$boardId'
import { Route as ColumnsColumnIdTasksCreateRouteImport } from './routes/columns/$columnId/tasks/create'
import { Route as BoardsBoardIdColumnsCreateRouteImport } from './routes/boards/$boardId/columns/create'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardsCreateRoute = BoardsCreateRouteImport.update({
  id: '/boards/create',
  path: '/boards/create',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardsBoardIdRoute = BoardsBoardIdRouteImport.update({
  id: '/boards/$boardId',
  path: '/boards/$boardId',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardsBoardIdIndexRoute = BoardsBoardIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BoardsBoardIdRoute,
} as any)
const TasksUpdateTaskIdRoute = TasksUpdateTaskIdRouteImport.update({
  id: '/tasks/update/$taskId',
  path: '/tasks/update/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksDeleteTaskIdRoute = TasksDeleteTaskIdRouteImport.update({
  id: '/tasks/delete/$taskId',
  path: '/tasks/delete/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)
const ColumnsUpdateColumnIdRoute = ColumnsUpdateColumnIdRouteImport.update({
  id: '/columns/update/$columnId',
  path: '/columns/update/$columnId',
  getParentRoute: () => rootRouteImport,
} as any)
const ColumnsDeleteColumnIdRoute = ColumnsDeleteColumnIdRouteImport.update({
  id: '/columns/delete/$columnId',
  path: '/columns/delete/$columnId',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardsUpdateBoardIdRoute = BoardsUpdateBoardIdRouteImport.update({
  id: '/boards/update/$boardId',
  path: '/boards/update/$boardId',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardsDeleteBoardIdRoute = BoardsDeleteBoardIdRouteImport.update({
  id: '/boards/delete/$boardId',
  path: '/boards/delete/$boardId',
  getParentRoute: () => rootRouteImport,
} as any)
const ColumnsColumnIdTasksCreateRoute =
  ColumnsColumnIdTasksCreateRouteImport.update({
    id: '/columns/$columnId/tasks/create',
    path: '/columns/$columnId/tasks/create',
    getParentRoute: () => rootRouteImport,
  } as any)
const BoardsBoardIdColumnsCreateRoute =
  BoardsBoardIdColumnsCreateRouteImport.update({
    id: '/columns/create',
    path: '/columns/create',
    getParentRoute: () => BoardsBoardIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/boards/$boardId': typeof BoardsBoardIdRouteWithChildren
  '/boards/create': typeof BoardsCreateRoute
  '/boards/delete/$boardId': typeof BoardsDeleteBoardIdRoute
  '/boards/update/$boardId': typeof BoardsUpdateBoardIdRoute
  '/columns/delete/$columnId': typeof ColumnsDeleteColumnIdRoute
  '/columns/update/$columnId': typeof ColumnsUpdateColumnIdRoute
  '/tasks/delete/$taskId': typeof TasksDeleteTaskIdRoute
  '/tasks/update/$taskId': typeof TasksUpdateTaskIdRoute
  '/boards/$boardId/': typeof BoardsBoardIdIndexRoute
  '/boards/$boardId/columns/create': typeof BoardsBoardIdColumnsCreateRoute
  '/columns/$columnId/tasks/create': typeof ColumnsColumnIdTasksCreateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/boards/create': typeof BoardsCreateRoute
  '/boards/delete/$boardId': typeof BoardsDeleteBoardIdRoute
  '/boards/update/$boardId': typeof BoardsUpdateBoardIdRoute
  '/columns/delete/$columnId': typeof ColumnsDeleteColumnIdRoute
  '/columns/update/$columnId': typeof ColumnsUpdateColumnIdRoute
  '/tasks/delete/$taskId': typeof TasksDeleteTaskIdRoute
  '/tasks/update/$taskId': typeof TasksUpdateTaskIdRoute
  '/boards/$boardId': typeof BoardsBoardIdIndexRoute
  '/boards/$boardId/columns/create': typeof BoardsBoardIdColumnsCreateRoute
  '/columns/$columnId/tasks/create': typeof ColumnsColumnIdTasksCreateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/boards/$boardId': typeof BoardsBoardIdRouteWithChildren
  '/boards/create': typeof BoardsCreateRoute
  '/boards/delete/$boardId': typeof BoardsDeleteBoardIdRoute
  '/boards/update/$boardId': typeof BoardsUpdateBoardIdRoute
  '/columns/delete/$columnId': typeof ColumnsDeleteColumnIdRoute
  '/columns/update/$columnId': typeof ColumnsUpdateColumnIdRoute
  '/tasks/delete/$taskId': typeof TasksDeleteTaskIdRoute
  '/tasks/update/$taskId': typeof TasksUpdateTaskIdRoute
  '/boards/$boardId/': typeof BoardsBoardIdIndexRoute
  '/boards/$boardId/columns/create': typeof BoardsBoardIdColumnsCreateRoute
  '/columns/$columnId/tasks/create': typeof ColumnsColumnIdTasksCreateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/boards/$boardId'
    | '/boards/create'
    | '/boards/delete/$boardId'
    | '/boards/update/$boardId'
    | '/columns/delete/$columnId'
    | '/columns/update/$columnId'
    | '/tasks/delete/$taskId'
    | '/tasks/update/$taskId'
    | '/boards/$boardId/'
    | '/boards/$boardId/columns/create'
    | '/columns/$columnId/tasks/create'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/boards/create'
    | '/boards/delete/$boardId'
    | '/boards/update/$boardId'
    | '/columns/delete/$columnId'
    | '/columns/update/$columnId'
    | '/tasks/delete/$taskId'
    | '/tasks/update/$taskId'
    | '/boards/$boardId'
    | '/boards/$boardId/columns/create'
    | '/columns/$columnId/tasks/create'
  id:
    | '__root__'
    | '/'
    | '/boards/$boardId'
    | '/boards/create'
    | '/boards/delete/$boardId'
    | '/boards/update/$boardId'
    | '/columns/delete/$columnId'
    | '/columns/update/$columnId'
    | '/tasks/delete/$taskId'
    | '/tasks/update/$taskId'
    | '/boards/$boardId/'
    | '/boards/$boardId/columns/create'
    | '/columns/$columnId/tasks/create'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoardsBoardIdRoute: typeof BoardsBoardIdRouteWithChildren
  BoardsCreateRoute: typeof BoardsCreateRoute
  BoardsDeleteBoardIdRoute: typeof BoardsDeleteBoardIdRoute
  BoardsUpdateBoardIdRoute: typeof BoardsUpdateBoardIdRoute
  ColumnsDeleteColumnIdRoute: typeof ColumnsDeleteColumnIdRoute
  ColumnsUpdateColumnIdRoute: typeof ColumnsUpdateColumnIdRoute
  TasksDeleteTaskIdRoute: typeof TasksDeleteTaskIdRoute
  TasksUpdateTaskIdRoute: typeof TasksUpdateTaskIdRoute
  ColumnsColumnIdTasksCreateRoute: typeof ColumnsColumnIdTasksCreateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boards/create': {
      id: '/boards/create'
      path: '/boards/create'
      fullPath: '/boards/create'
      preLoaderRoute: typeof BoardsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boards/$boardId': {
      id: '/boards/$boardId'
      path: '/boards/$boardId'
      fullPath: '/boards/$boardId'
      preLoaderRoute: typeof BoardsBoardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boards/$boardId/': {
      id: '/boards/$boardId/'
      path: '/'
      fullPath: '/boards/$boardId/'
      preLoaderRoute: typeof BoardsBoardIdIndexRouteImport
      parentRoute: typeof BoardsBoardIdRoute
    }
    '/tasks/update/$taskId': {
      id: '/tasks/update/$taskId'
      path: '/tasks/update/$taskId'
      fullPath: '/tasks/update/$taskId'
      preLoaderRoute: typeof TasksUpdateTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/delete/$taskId': {
      id: '/tasks/delete/$taskId'
      path: '/tasks/delete/$taskId'
      fullPath: '/tasks/delete/$taskId'
      preLoaderRoute: typeof TasksDeleteTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/columns/update/$columnId': {
      id: '/columns/update/$columnId'
      path: '/columns/update/$columnId'
      fullPath: '/columns/update/$columnId'
      preLoaderRoute: typeof ColumnsUpdateColumnIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/columns/delete/$columnId': {
      id: '/columns/delete/$columnId'
      path: '/columns/delete/$columnId'
      fullPath: '/columns/delete/$columnId'
      preLoaderRoute: typeof ColumnsDeleteColumnIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boards/update/$boardId': {
      id: '/boards/update/$boardId'
      path: '/boards/update/$boardId'
      fullPath: '/boards/update/$boardId'
      preLoaderRoute: typeof BoardsUpdateBoardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boards/delete/$boardId': {
      id: '/boards/delete/$boardId'
      path: '/boards/delete/$boardId'
      fullPath: '/boards/delete/$boardId'
      preLoaderRoute: typeof BoardsDeleteBoardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/columns/$columnId/tasks/create': {
      id: '/columns/$columnId/tasks/create'
      path: '/columns/$columnId/tasks/create'
      fullPath: '/columns/$columnId/tasks/create'
      preLoaderRoute: typeof ColumnsColumnIdTasksCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boards/$boardId/columns/create': {
      id: '/boards/$boardId/columns/create'
      path: '/columns/create'
      fullPath: '/boards/$boardId/columns/create'
      preLoaderRoute: typeof BoardsBoardIdColumnsCreateRouteImport
      parentRoute: typeof BoardsBoardIdRoute
    }
  }
}

interface BoardsBoardIdRouteChildren {
  BoardsBoardIdIndexRoute: typeof BoardsBoardIdIndexRoute
  BoardsBoardIdColumnsCreateRoute: typeof BoardsBoardIdColumnsCreateRoute
}

const BoardsBoardIdRouteChildren: BoardsBoardIdRouteChildren = {
  BoardsBoardIdIndexRoute: BoardsBoardIdIndexRoute,
  BoardsBoardIdColumnsCreateRoute: BoardsBoardIdColumnsCreateRoute,
}

const BoardsBoardIdRouteWithChildren = BoardsBoardIdRoute._addFileChildren(
  BoardsBoardIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoardsBoardIdRoute: BoardsBoardIdRouteWithChildren,
  BoardsCreateRoute: BoardsCreateRoute,
  BoardsDeleteBoardIdRoute: BoardsDeleteBoardIdRoute,
  BoardsUpdateBoardIdRoute: BoardsUpdateBoardIdRoute,
  ColumnsDeleteColumnIdRoute: ColumnsDeleteColumnIdRoute,
  ColumnsUpdateColumnIdRoute: ColumnsUpdateColumnIdRoute,
  TasksDeleteTaskIdRoute: TasksDeleteTaskIdRoute,
  TasksUpdateTaskIdRoute: TasksUpdateTaskIdRoute,
  ColumnsColumnIdTasksCreateRoute: ColumnsColumnIdTasksCreateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
